# Generated by Django 4.2.5 on 2024-02-06 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_list',
            name='Model',
            field=models.ForeignKey(default='default_model', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='home.model'),
        ),
    ]
