# Generated by Django 4.2.5 on 2024-02-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_item_list_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_list',
            name='art_nr',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
